// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDrWm7FmEAV15yLxB7FGxN_vpCMjKf_CQ',
    appId: '1:582157676991:web:c7fe372f4d17e2a7df310a',
    messagingSenderId: '582157676991',
    projectId: 'doe-conecta',
    authDomain: 'doe-conecta.firebaseapp.com',
    storageBucket: 'doe-conecta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBOYcpvCqE-LjowGvANxYTrE2UA-3PxA',
    appId: '1:582157676991:android:d3364d3df06f2fcfdf310a',
    messagingSenderId: '582157676991',
    projectId: 'doe-conecta',
    storageBucket: 'doe-conecta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbiz-s31VBGkFz9ds4NaBx-CsC1l6U5as',
    appId: '1:57002127976:ios:cdee98ece7034c271e41dd',
    messagingSenderId: '57002127976',
    projectId: 'lojaflutter-eb396',
    storageBucket: 'lojaflutter-eb396.appspot.com',
    iosBundleId: 'br.com.dtec.loja.loja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbiz-s31VBGkFz9ds4NaBx-CsC1l6U5as',
    appId: '1:57002127976:ios:cdee98ece7034c271e41dd',
    messagingSenderId: '57002127976',
    projectId: 'lojaflutter-eb396',
    storageBucket: 'lojaflutter-eb396.appspot.com',
    iosBundleId: 'br.com.dtec.loja.loja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVAMU2Rd8GHn-g-ZyOw6N8UM28jCobYcU',
    appId: '1:57002127976:web:35fe15a1de80e56e1e41dd',
    messagingSenderId: '57002127976',
    projectId: 'lojaflutter-eb396',
    authDomain: 'lojaflutter-eb396.firebaseapp.com',
    storageBucket: 'lojaflutter-eb396.appspot.com',
  );
}